### PR TITLE
adds support for max_replicas_per_node and placement preferences

### PR DESCRIPTION
**Pull request by dvallant**
Adds support for parsing the following attributes that belong to the deploy section:

- [max_replicas_per_node](https://docs.docker.com/compose/compose-file/#max_replicas_per_node)
- [placement preferences](https://docs.docker.com/compose/compose-file/#placement)

### CODE REVIEW

**Comment by dvallant** [comment]
This patch is a necessary preparation to add support for max_replicas_per_node and placement preferences to [docker-client](https://github.com/gesellix/docker-client/). If you accept it i will create a corresponding pull request for docker-client.

**Comment by dvallant** [comment]
Any chance this pull request will be merged?

**Comment by gesellix** [comment]
@dvallant I'm very sorry, I didn't notice your PR until today. I'll review it this week!

**Comment by dvallant** [comment]
> @dvallant I'm very sorry, I didn't notice your PR until today. I'll review it this week!

Hey, no problem. I only asked, 'cause i have another PR for [docker-client](https://github.com/gesellix/docker-client/) which needs this one :-) no hurry and thx

**Comment by gesellix** [comment]
The new version has been released as [2020-06-18T15-03-44](https://bintray.com/beta/#/gesellix/docker-utils/docker-compose/)

**Pull request merged**
